name: flutterohddul
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  candlesticks: ^2.1.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  desktop_window: ^0.4.0
  go_router: ^12.1.1
  kakao_flutter_sdk: ^1.7.0
  envied: ^0.5.2
  provider: ^6.1.1
  k_chart: ^0.7.1
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  http_parser: ^4.0.2
  pie_chart: ^5.4.0
  country_flags: ^2.2.0
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/group/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/font/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/font/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/font/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/font/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/font/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSansKR-Black.ttf
          weight: 900
